"""Prompt registry — prompts are versioned FILES, not inline f-strings (D6, D10, D18).

Three consequences of this choice:
  * a prompt change shows up in `git diff` and goes through the eval gate (D19);
  * the prompt's version participates in the cache key (D10) — a prompt edit cannot
    silently serve answers generated by the previous prompt;
  * the content sha is recorded in traces, so a production answer is attributable to an
    exact prompt revision.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

PROMPTS_DIR = Path(__file__).parent / "prompts"


@dataclass(frozen=True, slots=True)
class Prompt:
    name: str
    version: str
    text: str
    sha256: str

    def render(self, **values: str) -> str:
        """Substitute {placeholders}. Raises KeyError if the template needs a value the
        caller did not supply — a missing `{context}` must fail loudly, not render 'None'."""
        return self.text.format(**values)


@lru_cache(maxsize=32)
def load_prompt(name: str, version: str = "v1") -> Prompt:
    path = PROMPTS_DIR / f"{name}_{version}.md"
    if not path.is_file():
        available = sorted(p.stem for p in PROMPTS_DIR.glob("*.md"))
        raise FileNotFoundError(f"prompt {name}_{version} not found; available: {available}")
    text = path.read_text(encoding="utf-8")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return Prompt(name=name, version=version, text=text, sha256=digest)


def list_prompts() -> list[str]:
    return sorted(p.stem for p in PROMPTS_DIR.glob("*.md"))
