"""Prompt registry. Prompts are versioned files rather than inline f-strings, which buys
three things:

  * a prompt change shows up in `git diff` and goes through the eval gate;
  * the prompt version is part of the cache key, so an edit can't silently serve answers
    generated by the previous prompt;
  * the content sha lands in traces, so an answer is attributable to an exact revision.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

PROMPTS_DIR = Path(__file__).parent / "prompts"


@dataclass(frozen=True, slots=True)
class Prompt:
    name: str
    version: str
    text: str
    sha256: str

    def render(self, **values: str) -> str:
        """Substitute {placeholders}. Raises KeyError if the caller didn't supply one, so
        a missing `{context}` fails loudly instead of rendering 'None'."""
        return self.text.format(**values)


@lru_cache(maxsize=32)
def load_prompt(name: str, version: str = "v1") -> Prompt:
    path = PROMPTS_DIR / f"{name}_{version}.md"
    if not path.is_file():
        available = sorted(p.stem for p in PROMPTS_DIR.glob("*.md"))
        raise FileNotFoundError(f"prompt {name}_{version} not found; available: {available}")
    text = path.read_text(encoding="utf-8")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return Prompt(name=name, version=version, text=text, sha256=digest)


def list_prompts() -> list[str]:
    return sorted(p.stem for p in PROMPTS_DIR.glob("*.md"))
