"""Initial schema DDL.

Hand-written rather than Alembic-autogenerated. SQLAlchemy's autogenerate doesn't emit
`PARTITION BY RANGE`, and a silently non-partitioned `messages` table would look identical
in tests while making the whole retention design impossible.

Alembic wraps this in the initial revision. The SQL lives here so it stays reviewable and
testable on its own.
"""

from __future__ import annotations

CREATE_SESSIONS = """
CREATE TABLE IF NOT EXISTS sessions (
    id            UUID PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_hash   VARCHAR(64)
);
"""

CREATE_SESSIONS_INDEX = """
CREATE INDEX IF NOT EXISTS ix_sessions_last_seen ON sessions (last_seen_at);
"""

# The primary key has to include the partition key or Postgres rejects the table.
CREATE_MESSAGES = """
CREATE TABLE IF NOT EXISTS messages (
    id          UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    session_id  UUID NOT NULL,
    role        VARCHAR(16) NOT NULL,
    content     TEXT NOT NULL,
    kind        VARCHAR(16),
    model_id    VARCHAR(128),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
"""

# No FK to sessions. Postgres can't enforce one from a partitioned table in every
# version/config combination, and ON DELETE CASCADE across partitions would negate the
# DROP-PARTITION retention strategy anyway. Referential integrity for history is enforced
# in the repository layer instead.
CREATE_MESSAGES_INDEX = """
CREATE INDEX IF NOT EXISTS ix_messages_session_created
    ON messages (session_id, created_at DESC);
"""


# Users and conversations.
#
# `users` stores the auth provider's subject and nothing else: no email, no name, no
# picture. The identity provider already holds the profile, and duplicating it here would
# add a PII store to defend, a deletion obligation, and a breach surface, in exchange for
# data this product never uses.
CREATE_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY,
    auth_subject  VARCHAR(255) NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""

# A conversation belongs to a user (signed in) or a session (anonymous), and the CHECK
# makes an ownerless row impossible rather than just unlikely.
#
# Both columns exist at once on purpose. An anonymous conversation records the session that
# created it, and signing in claims those conversations by setting user_id. Without that
# seam, signing in orphans everything asked beforehand, which is the conversation that
# usually convinced someone to sign up in the first place.
#
# The FK to users cascades, safe here because `conversations` isn't partitioned. `messages`
# still has no FK, since a cascade across partitions would defeat DROP PARTITION.
CREATE_CONVERSATIONS = """
CREATE TABLE IF NOT EXISTS conversations (
    id          UUID PRIMARY KEY,
    user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
    session_id  UUID,
    title       VARCHAR(200),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT conversations_have_an_owner
        CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);
"""

# One statement per constant. asyncpg prepares each one, and a prepared statement can't
# contain multiple commands, so bundling these two produced `cannot insert multiple
# commands into a prepared statement` on every boot.
CREATE_CONVERSATIONS_USER_INDEX = """
CREATE INDEX IF NOT EXISTS ix_conversations_user_updated
    ON conversations (user_id, updated_at DESC);
"""

CREATE_CONVERSATIONS_SESSION_INDEX = """
CREATE INDEX IF NOT EXISTS ix_conversations_session_updated
    ON conversations (session_id, updated_at DESC);
"""

# ADD COLUMN IF NOT EXISTS on a partitioned table cascades to every partition, so this is
# idempotent and safe to run on every boot like the rest of the DDL.
#
# Nullable, and session_id stays. Existing rows predate conversations, and dropping the old
# column would break the anonymous read path. The two answer different questions:
# session_id is "this visitor's transcript", conversation_id is "this thread". Removing
# session_id is a separate migration once nothing reads it.
ALTER_MESSAGES_ADD_CONVERSATION = """
ALTER TABLE messages ADD COLUMN IF NOT EXISTS conversation_id UUID;
"""

CREATE_MESSAGES_CONVERSATION_INDEX = """
CREATE INDEX IF NOT EXISTS ix_messages_conversation_created
    ON messages (conversation_id, created_at DESC);
"""

DROP_ALL = """
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
"""

# Pinning a conversation to the top of the sidebar.
#
# ADD COLUMN IF NOT EXISTS with a DEFAULT, because this runs on every boot against a
# database that already has rows, so it has to be safe to re-apply and safe on a populated
# table. NOT NULL DEFAULT FALSE needs no backfill: Postgres 11+ stores the default in the
# catalogue instead of rewriting the table, so it stays O(1) even at 10M rows.
#
# A column rather than a `pins` table, since a pin is one boolean owned by the row it
# describes, with no history and no per-device variation. A join table would be right if
# pins were per-device, and they aren't: a pin follows the account, which is why this moved
# out of the browser.
ALTER_CONVERSATIONS_ADD_PINNED = """
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;
"""

# Partial index: only pinned rows are indexed, because only pinned rows are ever filtered
# on. On a table where almost everything is unpinned this is a fraction of the size of a
# full index and answers the only query that uses it.
CREATE_CONVERSATIONS_PINNED_INDEX = """
CREATE INDEX IF NOT EXISTS conversations_pinned_idx
    ON conversations (user_id, session_id, updated_at DESC)
    WHERE pinned;
"""

INITIAL_DDL: tuple[str, ...] = (
    CREATE_SESSIONS,
    CREATE_SESSIONS_INDEX,
    CREATE_MESSAGES,
    CREATE_MESSAGES_INDEX,
    # S20. Order matters: users before conversations (FK), conversations before the
    # messages column that references them by id.
    CREATE_USERS,
    CREATE_CONVERSATIONS,
    CREATE_CONVERSATIONS_USER_INDEX,
    CREATE_CONVERSATIONS_SESSION_INDEX,
    ALTER_MESSAGES_ADD_CONVERSATION,
    CREATE_MESSAGES_CONVERSATION_INDEX,
    # S22. After CREATE_CONVERSATIONS, since it alters that table.
    ALTER_CONVERSATIONS_ADD_PINNED,
    CREATE_CONVERSATIONS_PINNED_INDEX,
)
