"""Initial schema DDL (D1).

Hand-written rather than Alembic-autogenerated: SQLAlchemy's autogenerate does not emit
`PARTITION BY RANGE`, and a silently non-partitioned `messages` table would look identical
in tests while making the entire retention design (DROP PARTITION) impossible. The one
piece of schema that must not be generated is the one Alembic can't generate.

Alembic wraps this in the initial revision; the SQL lives here so it is reviewable and
testable on its own.
"""

from __future__ import annotations

CREATE_SESSIONS = """
CREATE TABLE IF NOT EXISTS sessions (
    id            UUID PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_hash   VARCHAR(64)
);
"""

CREATE_SESSIONS_INDEX = """
CREATE INDEX IF NOT EXISTS ix_sessions_last_seen ON sessions (last_seen_at);
"""

# PRIMARY KEY must include the partition key — Postgres rejects the table otherwise.
CREATE_MESSAGES = """
CREATE TABLE IF NOT EXISTS messages (
    id          UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    session_id  UUID NOT NULL,
    role        VARCHAR(16) NOT NULL,
    content     TEXT NOT NULL,
    kind        VARCHAR(16),
    model_id    VARCHAR(128),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
"""

# NOTE: no FK to sessions. Postgres cannot enforce a foreign key from a partitioned table
# in every version/config combination, and more importantly ON DELETE CASCADE across
# partitions would negate the DROP-PARTITION retention strategy. Referential integrity for
# history is enforced in the repository layer instead — a deliberate trade recorded here.
CREATE_MESSAGES_INDEX = """
CREATE INDEX IF NOT EXISTS ix_messages_session_created
    ON messages (session_id, created_at DESC);
"""

DROP_ALL = """
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
"""

INITIAL_DDL: tuple[str, ...] = (
    CREATE_SESSIONS,
    CREATE_SESSIONS_INDEX,
    CREATE_MESSAGES,
    CREATE_MESSAGES_INDEX,
)
